### ISSUE TITLE
Loader icon

### ISSUE THREAD

**Issue by 0xVenky** [SwaprDAO/swapr-info#54]
When we open dxstats, the loader looks like this below:

![image](https://user-images.githubusercontent.com/55109759/165073822-974bff4f-78d8-4f5d-b914-080e8962e53b.png)

2 things to update if possible,

1. Update the loader to look similar to how the loader is in Swapr (when loading the Swapr balance)
2. The value of the liquidity is available (as we can see from the charts), but for some reason the loader keeps on and on for about 20 seconds. Would be good to display the current time's liquidity and figure out what is causing this loading.

**Comment by wixzi** [comment]
The liquidity for the chart and total is calculated separately in different calls. Need to look why we do that.
