### ISSUE TITLE
Fix layout and number layout issue

### ISSUE THREAD

**Issue by wixzi** [SwaprDAO/swapr-info#91]
![screencapture-deploy-preview-89-swapr-analytics-netlify-app-2022-07-17-22_19_48](https://user-images.githubusercontent.com/102727631/179423648-c3bb3bbc-ea54-422f-a744-2fc0dee5f80f.png)

**Comment by guerrap** [comment]
Why do the carts and the left menu look broken?

**Comment by guerrap** [comment]
Fixed in #89
